#!/bin/bash -e
# package_rpi_gpio_ntp.sh

INIT_PACKAGE_DIR=$(pwd)/rpi-gpio-ntp
UPSTREAM_VERSION=1.0
VERSION=${UPSTREAM_VERSION}-${CIRCLE_BUILD_NUM:-non-circle}
PACKAGE_DIR="rpi-gpio-ntp_${CIRCLE_BRANCH}_${VERSION}"

EXECUTABLE=$1
if [[ ! -f ${EXECUTABLE} ]] | [[ $(basename ${EXECUTABLE}) != "rpi_gpio_ntp" ]]; then
  echo "ERR: No rpi_gpio_ntp file found at specified location."
  exit 2
fi

mkdir -p ${PACKAGE_DIR}
rsync -a ${INIT_PACKAGE_DIR} ${PACKAGE_DIR}/

cp ${EXECUTABLE} ${PACKAGE_DIR}/usr/bin/

cd ${PACKAGE_DIR}/DEBIAN
if ! [ "${CIRCLE_BRANCH}" == "master" ]; then
    sed -i 's@Package: rpi-gpio-ntp@Package: rpi-gpio-ntp-'$CIRCLE_BRANCH'@' control
fi
sed -i 's@Version:@Version: '$VERSION'@' control
cat control
cd ${REPO}
ls ${PACKAGE_DIR}
dpkg-deb --build ${PACKAGE_DIR}

exit 0
