version: 2.1
executors:
  kairos-continuous-base:
    docker:
      - image: 137296740171.dkr.ecr.us-west-2.amazonaws.com/kairos-focal:circleci
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    working_directory: /opt/kairos/build-home/repo
commands:
  setup-build-container:
    description: standard python build flow
    steps:
      - checkout
      - run: kairos_container_init
jobs:
  build:
    executor: kairos-continuous-base
    working_directory: /opt/kairos/build-home/repo
    environment:
      MAJOR_VERSION: 1
    steps:
      - checkout

      - run: kairos_container_init

      - run:
          name: Build
          command: |
            sudo apt-get update && sudo apt-get install build-essential
            cd rpi-gpio-ntp
            make -j 8

      - run:
          name: Package
          command: |
            ./package_rpi_gpio_ntp /opt/kairos/build-home/repo/rpi-gpio-ntp/rpi_gpio_ntp
            mkdir /opt/kairos/build-home/repo/build_artifacts
            cp rpi-gpio-ntp*.deb /opt/kairos/build-home/repo/build_artifacts

      - store_artifacts:
          path: /opt/kairos/build-home/repo/build_artifacts
          destination: build-artifacts

      - run: ./publish-to-artifactory

notify:
  webhooks:
    - url: https://bdoa77w3h0.execute-api.us-west-2.amazonaws.com/webhook/
workflows:
  version: 2
  kairos-workflow:
    jobs:
      - build:
          context: org-global
