version: 2.1
executors:
  kairos-continuous-base:
    docker:
      - image: 137296740171.dkr.ecr.us-west-2.amazonaws.com/kairos-focal:circleci
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    working_directory: /opt/kairos/build-home/repo
commands:
  setup-build-container:
    description: standard python build flow
    steps:
      - checkout
      - run: kairos_container_init
jobs:
  build:
    executor: kairos-continuous-base
    working_directory: /opt/kairos/build-home/repo
    environment:
      MAJOR_VERSION: 1
    steps:
      - checkout

      - run: kairos_container_init

      - run:
          name: Build
          command: |
            cd rpi-gpio-ntp
            make -j 8

      - run:
          name: Package
          command: |
            ls
            ./package_rpi_gpio_ntp
            ls

      - store_artifacts:
          path: dist
          destination: build-artifacts

#      - run: ./circle_scripts/publish-to-artifactory
#
#      - run: curl -u $KAIROS_PUBLISH_USER:$KAIROS_PUBLISH_API_KEY -X POST "https://kairosaerospace.jfrog.io/kairosaerospace/api/deb/reindex/kairos-apt?writeProps=0"
#
#      - deploy:
#          name: conditionally run a deploy job
#          command: |
#            if [[ $CIRCLE_BRANCH == "master" ]]; then
#              ./circle_scripts/trigger_build kairos-docker-flightsim:x-ubuntu20
#            fi

notify:
  webhooks:
    - url: https://bdoa77w3h0.execute-api.us-west-2.amazonaws.com/webhook/
workflows:
  version: 2
  kairos-workflow:
    jobs:
      - build:
          context: org-global
